# Generated by Django 3.1.1 on 2021-11-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20211127_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
