# Generated by Django 3.1.1 on 2021-11-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_20211128_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liga',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
