# Generated by Django 3.1.1 on 2021-11-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_patata'),
    ]

    operations = [
        migrations.AddField(
            model_name='liga',
            name='imagen_liga',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
