# Generated by Django 3.1.1 on 2021-12-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_auto_20211228_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(blank=True, default='default.png', upload_to='image/liga/'),
        ),
    ]
