# Generated by Django 3.1.1 on 2021-12-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_equipo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(blank=True, default='default.png', upload_to='image/equipo/'),
        ),
    ]
