# Generated by Django 3.1.1 on 2021-12-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LigaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameliga', models.CharField(max_length=50)),
                ('anyocreacion', models.CharField(max_length=50)),
                ('maxganador', models.CharField(max_length=50)),
                ('ultimoganador', models.CharField(max_length=50)),
            ],
        ),
    ]
