# Generated by Django 3.1.1 on 2021-12-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligainfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligainfo',
            name='numequipos',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AlterField(
            model_name='ligainfo',
            name='nameliga',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
