# Generated by Django 3.1.1 on 2021-12-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
