# Generated by Django 3.2.9 on 2021-11-27 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_equipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deporte',
            old_name='nombre',
            new_name='nombre_deporte',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='nombre',
            new_name='nombre_equipo',
        ),
        migrations.RenameField(
            model_name='liga',
            old_name='nombre',
            new_name='nombre_liga',
        ),
    ]
